### ISSUE TITLE
Added ability to listen to music

### ISSUE THREAD

**Issue by BaptistePgn** [BaptistePgn/KroniqBOT#1]
**Objective:**
Enable our Discord bot to have the ability to listen to music, thus providing an enhanced experience to users.

**Features to implement:**
1. Integration of music playback functionality via specific commands.
2. Management of the music queue.
3. Playback controls (play, pause, stop, skip track, etc.).
4. Ability to search for and add tracks to the queue.
5. Support for various music streaming services (e.g., YouTube, Spotify, SoundCloud).

**Tasks to accomplish:**
- [x] Development of music playback functionality.
- [x] Implementation of queue management.
- [x] Addition of playback control commands.
- [x] Integration of track search and add functionality.
- [x] Support for streaming services integration.
